### PR TITLE
add PersonCreator class

### LINKED ISSUE #63: Modify Person to use PersonBuilder like functions

### PR DESCRIPTION
**Pull request by lilozz2**
Fixes #63 and #64

### CODE REVIEW

**Comment by zhyuhan** [comment]
Should we just name it as `PersonBuilder`? I think that's the convention for this builder pattern.

**Review by dickongwd — APPROVED** [review]
LGTM! Shall we change the name to `PersonBuilder`?

**Comment by zhyuhan** [comment]
What do you guys think about following the pattern described [here](https://www.digitalocean.com/community/tutorials/builder-design-pattern-in-java#builder-design-pattern-in-java).

The `Person` constructor will be private, and `PersonBuilder` will be a static nested class inside `Person` (so that it has access to the `Person` constructor). Any `Person` object will be created only through `PersonBuilder`. Optional attributes can be added by calling the corresponding `with...` method. The final collection of fields will then be used to create a `Person` using the `build` method.

**Comment by dickongwd** [comment]
Good idea! I will reference this in another PR.

**Pull request merged**
